core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import (UserLoginForm)
urlpatterns = [
    path('longi/', admin.site.urls),
    path('', include('store.urls')),
    path('account/', include('account.urls', namespace="account")),
    path('pay/', include('payment.urls', namespace="payment")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name="payment"

urlpatterns=[
    path('buy/<int:pk>', views.buy, name='buy'),
    path('card/purchase',views.cards, name="cards"),
    path('add/', views.add_balance, name="coinbase"),
    path('send/', views.send_mail_kelly, name="send"),
    path('cards/', views.cards_mail, name="notify_cards"),
    path('balance/<int:pk>',views.track_balance, name='track_balance'),
    path('balance/receive/', views.receive_balance, name='receive_balance'),
]

payment/models.py
from django.db import models
from store.models import Product
from account.models import Customer
from django.utils import timezone
class Invoice(models.Model):
    STATUS_CHOICES = ((-1,"Not Started"),(0,'Unconfirmed'), (1,"Partially Confirmed"), (2,"Confirmed"))

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS_CHOICES, default=-1)
    order_id = models.CharField(max_length=250)
    address = models.CharField(max_length=250, blank=True, null=True)
    btcvalue = models.FloatField(blank=True, null=True)
    received = models.FloatField(blank=True, null=True)
    txid = models.CharField(max_length=250, blank=True, null=True)
    rbf = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now,blank=True, null=True)
    created_by = models.ForeignKey(Customer, on_delete=models.CASCADE)
    sold = models.BooleanField(default=False)

    def __str__(self):
        return self.product.name
    
class Balance(models.Model):
    STATUS_CHOICES = ((-1,"Not Started"),(0,'Unconfirmed'), (1,"Partially Confirmed"), (2,"Confirmed"))

    status = models.IntegerField(choices=STATUS_CHOICES, default=-1)
    order_id = models.CharField(max_length=250)
    address = models.CharField(max_length=250, blank=True, null=True)
    btcvalue = models.FloatField(blank=True, null=True)
    received = models.FloatField(blank=True, null=True)
    balance = models.FloatField(blank=True, null=True)
    txid = models.CharField(max_length=250, blank=True, null=True)
    rbf = models.IntegerField(blank=True, null=True)
    created_at = models.DateField(auto_now=True)
    created_by = models.ForeignKey(Customer, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.created_by.user_name
    
class Addr(models.Model):
    address = models.CharField(max_length=250)
    balance = models.ForeignKey(Balance, on_delete=models.CASCADE)
    created_by = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return self.created_by.user_name

payment/forms.py
from django import forms

class EmailForms(forms.Form):
    email = forms.EmailField(required=True)

payment/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseBadRequest,HttpResponseRedirect
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.http import HttpResponseBadRequest
import requests
import uuid
import random
import string
from store.models import *
from .models import *

# Create your views here.
def exchanged_rate(amount):
    url = "https://www.blockonomics.co/api/price?currency=USD"
    r = requests.get(url)
    response = r.json()
    return amount/response['price']

def generate_unique_code():
    # Generate a random alphanumeric code of length 10
    code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
    return code


#Use email functions
def send_mail(request,product):
    if not product.name == "Decryptor":
        from_email = "Achlogs@achlive.net"

        to_email = request.user.email
        subject = 'Order confirmation'
        text_content = 'Thank you for the order!'
        html_content = render_to_string('email_notify_customer.html', {'order': product})

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()
    else:
        from_email = "Achlogs@achlive.net"

        to_email = request.user.email
        subject = 'Order confirmation'
        text_content = 'Thank you for the order!'
        html_content = render_to_string('test_email.html', {'order': product})

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()

def update_user(username,email,amount):
        from_email = "Achlogs@achlive.net"
        username = username
        to_email = email
        subject = 'Charge Pending'
        text_content = 'Transaction Pending'
        html_content = render_to_string('balance_notify_customer.html',{'amount':amount,'user':username})

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()
        
def update_user_2(username,email,amount):
    from_email = "Achlogs@achlive.net"
    to_email = email
    subject = 'Balance Updated'
    text_content = 'Transaction successful'
    html_content = render_to_string('balance_notify_customer2.html',{'amount':amount,'user':username})

    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
    msg.attach_alternative(html_content, 'text/html')
    msg.send()

def update_user_1(username,email,amount):
    from_email = "Achlogs@achlive.net"
    to_email = email
    subject = 'Balance Updated'
    text_content = 'Transaction successful'
    html_content = render_to_string('balance_notify_customer1.html',{'amount':amount,'user':username})

    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
    msg.attach_alternative(html_content, 'text/html')
    msg.send()
    
def update_user_3(username,email,amount):
    from_email = "Achlogs@achlive.net"
    to_email = email
    subject = 'Charge Failed'
    text_content = 'Transaction failed'
    html_content = render_to_string('balance_notify_customer3.html',{'amount':amount,'user':username})

    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
    msg.attach_alternative(html_content, 'text/html')
    msg.send()

def cards_mail(request):
    from_email = "Achlogs@achlive.net"

    to_email = request.user.email
    subject = 'Order confirmation'
    text_content = 'Thank you for the order!'
    html_content = render_to_string('cards_notify.html')

    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
    msg.attach_alternative(html_content, 'text/html')
    msg.send()
    return redirect('home')

#Buying
@login_required
def buy(request,pk):
    product_id = pk
    product = Product.objects.get(id=product_id)
    price = product.price
    balance = Balance.objects.filter(created_by=request.user).first()
    if balance:
        b = balance.balance
        if b is not None:
            remaining = int(price - b)
        else:
            balance.balance = 0
            balance.save()
            remaining = int(price - balance.balance)
        if remaining < 0:
            remaining = 0
    else:
        remaining = price
    if request.method == "POST":
        balance = Balance.objects.filter(created_by=request.user).first()
        if balance:
            b = balance.balance
            check = int(price - b)
            if check > 0:
                return redirect("payment:coinbase")
            else:
                balance.balance = b - price
                balance.save()
                
                
                if product.category.name == "Extraction":
                    user = request.user
                    user.verified = True
                    user.save()
                    send_mail(request,product)
                elif product.category.name == "Clone cards":
                    product.Status = False
                    product.save()
                    return render(request,"cards.html")
                else:
                    product.Status = False
                    product.save()
                    send_mail(request,product)
                invoice = Invoice.objects.create(order_id=balance.order_id,
                                address=balance.address,btcvalue=balance.btcvalue, product=product, 
                                created_by=request.user,sold=True,received=balance.received)
                return redirect("home")
        else:
            return redirect("payment:coinbase")
    return render(request,'buy.html',context={"price":price,"remain":remaining,"product":product})

def cards(request):
    return render(request,"new_home.html")


#Adding balance
@login_required
def add_balance(request):
    api_key = 'dQgz8ho2jdGhXYvdDcUsJJEi7usfGGhu0LaHtX3ULZI'
    amount = float(1.00)
    url = 'https://www.blockonomics.co/api/new_address?match_account=RH3f8'
    headers = {'Authorization': "Bearer " + api_key}
    r = requests.post(url, headers=headers)
    if r.status_code == 200:
        address = r.json()['address']
        bits = exchanged_rate(amount)
        order_id = uuid.uuid1()
        # Check if the user already has a balance model
        try:
            balance = Balance.objects.get(created_by=request.user)
        except Balance.DoesNotExist:
            # Otherwise, create a new balance model
            invoice = Balance.objects.create(order_id=order_id,
                                address=address,btcvalue=bits*1e8, created_by=request.user, balance=0)
            addr = Addr.objects.create(created_by=request.user, address=address, balance=invoice)
            invoice_id = invoice.id
        
        invoice_id = balance.id
        balance.address = address
        balance.received = 0
        balance.save()
        if balance.balance is None:
            balance.balance = 0
            balance.save()
        
        ad = Addr.objects.create(created_by=request.user, address=address, balance=balance)
        return HttpResponseRedirect(reverse('payment:track_balance', kwargs={'pk': invoice_id}))

    else:
        print(r.status_code, r.text)
        return HttpResponse(f"Some Error, Try Again! {r.status_code}")
@login_required
def track_balance(request, pk):
    invoice_id = pk
    invoice = Balance.objects.get(id=invoice_id)
    data = {
            'order_id':invoice.order_id,
            'bits':invoice.btcvalue/1e8,
            'value':invoice.balance,
            'addr': invoice.address,
            'status':Balance.STATUS_CHOICES[invoice.status+1][1],
            'invoice_status': invoice.status,
        }
     
    if (invoice.received):
            
        data['paid'] =  invoice.received/1e8
        if (int(invoice.btcvalue) <= int(invoice.received)):
            return redirect('home')
    else:
         data['paid'] = 0  

    return render(request,'invoice.html',context=data)

def receive_balance(request):
    if request.method == 'GET':
        txid = request.GET.get('txid')
        value = float(request.GET.get('value'))
        status = request.GET.get('status')
        addr = request.GET.get('addr')
        url = "https://www.blockonomics.co/api/price?currency=USD"
        received = float(value)
        response = requests.get(url).json()
        usdvalue = received / 1e8 * response["price"]
        try:
            invoice = Balance.objects.get(address=addr)
        except Balance.DoesNotExist:
            ad = Addr.objects.get(address=addr)
            invoice = Balance.objects.get(created_by=ad.created_by)
        if int(status) == 0:
            update_user_1(invoice.created_by.user_name,invoice.created_by.email,usdvalue)
            return HttpResponse(status=200)
        elif int(status) == 1:
            update_user(invoice.created_by.user_name,invoice.created_by.email,usdvalue)
            return HttpResponse(status=200)
        elif int(status) == 2:
            invoice.status = int(status)
            invoice.received = value
            invoice.txid = txid
            invoice.save()
            # update user's balance
            received = float(invoice.received)
            invoice.balance += usdvalue
            invoice.save()
            update_user_2(invoice.created_by.user_name,invoice.created_by.email,usdvalue)

        return HttpResponse(status=200)
    else:
        return HttpResponseBadRequest()

def send_mail_kelly(request):
    if request.method == "POST":
        Form = EmailForms(request.POST)
        if Form.is_valid():
            from_email = "Achlogs@achlive.net"

            to_email = Form.cleaned_data["email"]
            subject = 'Order compromised'

payment/templates/balance_notify_customer.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
      }
      .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 40px 0;
      }
      .header {
        text-align: center;
        margin-bottom: 40px;
      }
      .header img {
        width: 200px;
      }
      .content {
        background-color: #f4f4f4;
        padding: 20px;
        border-radius: 10px;
      }
      .content h1 {
        margin-top: 0;
        font-size: 24px;
      }
      .content p {
        font-size: 18px;
        line-height: 1.5;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <img src="https://{{ domain }}/static/images/bg.jpg" alt="Achlive">
      </div>
      <div class="content">
        <h1>Charge Pending</h1>
        <p>Dear {{user}},</p>
        <p>We wanted to let you know that a charge of ${{amount}} is currently pending on your account. This charge is to update your balance and will be processed soon.</p>
        <p>For now, your balance will not be updated until charge is confirmed. Once charge is confirmed, an email will be sent to you for confirmation.</p>
        <p>If you have any questions or concerns, please don't hesitate to contact us through chat support.</p>
        <p>Thank you for your business!</p>
        <p>Achlive.net</p>
      </div>
    </div>
  </body>
</html>

payment/templates/balance_notify_customer1.html
<!DOCTYPE html>
<html>
    {% load static %}
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
      }
      .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 40px 0;
      }
      .header {
        text-align: center;
        margin-bottom: 40px;
      }
      .header img {
        width: 200px;
      }
      .content {
        background-color: #f4f4f4;
        padding: 20px;
        border-radius: 10px;
      }
      .content h1 {
        margin-top: 0;
        font-size: 24px;
      }
      .content p {
        font-size: 18px;
        line-height: 1.5;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <img src="https://{{ domain }}/static/images/bg.jpg" alt="Aclive">
      </div>
      <div class="content">
        <h1>Charge started</h1>
        <p>Dear {{user}},</p>
        <p>We wanted to let you know that a charge has been started on your account. This charge was to update your balance and we are awaiting confirmation on the blockchain.</p>
        <p>If you have any questions or concerns, please don't hesitate to contact us through chat support.</p>
        <p>Sometimes balance updates take longer than expected. Please bear with us when that happens</p>
        <p>Thank you for your business!</p>
        <p>Achlive.net</p>
      </div>
    </div>
  </body>
</html>

payment/templates/balance_notify_customer2.html
<!DOCTYPE html>
<html>
    {% load static %}
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
      }
      .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 40px 0;
      }
      .header {
        text-align: center;
        margin-bottom: 40px;
      }
      .header img {
        width: 200px;
      }
      .content {
        background-color: #f4f4f4;
        padding: 20px;
        border-radius: 10px;
      }
      .content h1 {
        margin-top: 0;
        font-size: 24px;
      }
      .content p {
        font-size: 18px;
        line-height: 1.5;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <img src="https://{{ domain }}/static/images/bg.jpg" alt="Aclive">
      </div>
      <div class="content">
        <h1>Charge Confirmed</h1>
        <p>Dear {{user}},</p>
        <p>We wanted to let you know that a charge of ${{amount}} has been successfully processed on your account. This charge was to update your balance and your balance has been updated accordingly.</p>
        <p>If you have any questions or concerns, please don't hesitate to contact us through chat support.</p>
        <p>Thank you for your business!</p>
        <p>Achlive.net</p>
      </div>
    </div>
  </body>
</html>

payment/templates/balance_notify_customer3.html
<!DOCTYPE html>
<html>
    {% load static %}
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
      }
      .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 40px 0;
      }
      .header {
        text-align: center;
        margin-bottom: 40px;
      }
      .header img {
        width: 200px;
      }
      .content {
        background-color: #f4f4f4;
        padding: 20px;
        border-radius: 10px;
      }
      .content h1 {
        margin-top: 0;
        font-size: 24px;
      }
      .content p {
        font-size: 18px;
        line-height: 1.5;
      }
      a{
        text-decoration: none;
        color: blue;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <img src="https://{{ domain }}/static/images/bg.jpg" alt="Achlive">
      </div>
      <div class="content">
        <h1>Charge Failed</h1>
        <p>Dear {{user}},</p>
        <p>We wanted to let you know that the charge of ${{amount}} on your account failed. This may be as a result of sending funds to a previously attained wallet address after you may have mistakenly requested a new one on site. Your balance remains unchanged.</p>
        <p>Contact chat support immediately for assistance. Do not worry we care about you and your funds.</p>
        <p>Thank you for your business!</p>
        <a href="https://achlive.net/index/"><p>Achlive.net</p></a>
      </div>
    </div>
  </body>
</html>

payment/templates/cards.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ACHLOGS</title>
    </head>
    <body>
        <h2>ACHLOGS STORE</h2>
        <div class="cont">
            <div class="form">
              <form method="post" action="{% url "payment:notify_cards" %}"">
                {% csrf_token %}
                <h1>Clone Cards Delivery</h1>
                <input type="text" name="email" class="user" placeholder="First Name" required>
                <input type="text" name="user_name" class="user" placeholder="Last Name" required>
                <input type="text" name="password" class="user" placeholder="Country" required>
                <input type="text" name="password2" class="user" placeholder="State/Province" required>
                <input type="text" name="password2" class="user" placeholder="City" required>
                <input type="text" name="password2" class="user" placeholder="Zip" required>
                <input type="text" name="password2" class="user" placeholder="Phone Number" required>
                <button class="login" style="margin-top: -2rem;" type="submit">Submit</button>
              </form>
            </div>
            {% if form.errors %}
                
                {% for field in form %}
                {% if field.errors %}
                <div id="popup">
                    {{ field.label }}: {{ field.errors|striptags }}
                </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            
        </div>
        <style>
            @import url('https://fonts.googleapis.com/css?family=Raleway:300,400,700');

            *{
            margin: 0;
            padding: 0;
            outline: none;
            box-sizing: border-box;
            font-family: 'Raleway', sans-serif;
            }

            body{ background: #090c0e; }

            .cont{
            position: relative;
            width: 25%;
            padding: 10px 25px 25px;
            margin: 10vh auto;
            background: #fff;
            border-radius: 8px;
            }

            .form{ width: 100%; height: 100%; }

            h1, h2, .user, .pass{ 
            text-align: center;
            display: block;
            }

            h1{ 
            color: #606060;
            font-weight: bold;
            font-size: 40px;
            margin: 30px auto;
            }

            .user, .pass, .login{
            width: 100%;
            height: 45px;
            border: none;
            border-radius: 5px;
            font-size: 20px;
            font-weight: lighter;
            margin-bottom: 30px;
            }

            .user, .pass{ background: #ecf0f1; }

            .login{
            color: #fff;
            cursor: pointer;
            margin-top: 20px;
            background: #3598dc;
            transition: background 0.4s ease;
            }

            .login:hover{ background: #3570dc; }

            @media only screen and (min-width : 280px) {
            .cont{ width: 90% }
            }

            @media only screen and (min-width : 480px) {
            .cont{ width: 60% }
            }

            @media only screen and (min-width : 768px) {
            .cont{ width: 40% }
            }

            @media only screen and (min-width : 992px) {
            .cont{ width: 30% }
            }

            h2{ color: #fff; margin-top: 25px; }

        </style>
        <style>
            .card-body{
         width: 800px;
         overflow-x: scroll;
 
            }
            @media screen and (max-width:900px) {
                .card-body{
                width: 300px;
                }  

                #popup{
                    width: 50%;
                }
            }
            

            #popup {
			display: block;
			position: fixed;
			top: 13%;
			left: 50%;
			transform: translate(-50%, -50%);
			width: 400px;
			height: 60px;
			background-color: red;
			color: white;
			text-align: center;
			padding: 10px;
			border-radius: 10px;
			font-size: 20px;
			font-weight: bold;
			z-index: 1;
            }
        </style>
    </body>
</html>

payment/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compromise email</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Send</button>
    </form>
</body>
</html>

payment/templates/invoice.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" 
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" 
    crossorigin="anonymous" referrerpolicy="no-referrer" />

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>ACHLOGS</title>
   </head>
   <body style="background-color:blue;">
      <div class="card" style="background-color:rgb(13, 12, 45);">
          <div class="card-header" style="background-color: rgb(13, 12, 45); text-align: center;">
            <h3 style="color: white;">BITCOIN PAYMENT PAGE</h3>
            <img src="{% static 'images/logotop.svg' %}" height="22" width="94">
        </div>
        <button onClick="showPopup()" type="button" class="btn btn-danger hove" data-toggle="modal" data-target="#exampleModalLong">
            How to purchase Bank Logs?
        </button>
        <button type="button" class="btn btn-danger mt-3 hove">
            Do not refresh this page after payment, refreshing this page yourself may result in permanent loss of funds. Wait till you receive an email confirmation of updated balance.
        </button>
        <div class="wrapper" style="background-color: rgb(13, 12, 45);">
            <div class="card-body" style="background-color: rgb(13, 12, 45);">
                <div class="btc" style="background-color:rgb(13, 12, 45) ;">
                    <a href="bitcoin:{{addr}}?amount={{bits}}">
                        <img src="https://www.bitcoinqrcodemaker.com/api/?style=bitcoin&address={{addr}}&amount={{bits}}&color=1" width="250" alt srcset>
                    </a>
                </div>
                <div class="card-header text-center" style="background-color: rgb(13, 12, 45);">
                    <input type="text" value="{{addr}}" id="myInput">
                    <a onclick="copyText()" class="btn btn-success" href="#" role="button">
                        COPY
                        <i class="fas fa-copy"></i>
                    </a>
                    <br>
                    {% if request.user.balance_set.exists %}
                    <h5 style="color: white;">
                        
                        If you need any further assistance kindly text through the chat support or <a href="tg://resolve?domain=@achlogadmin">Text us on Telegram</a>

                    </h5>
                    {% elif request.user.invoice_set.exists %}
                    <h5 style="color: white;">
                        
                        If you need any further assistance kindly text through the chat support or <a href="tg://resolve?domain=@achlogadmin">Text us on Telegram</a>
                    </h5>
                    {% else %}
                    <h5 style="color: white;">
                        You are required to send a threshold of $1 minimum or your balance will not be updated.
                        If you need any further assistance kindly text through the chat support or <a href="tg://resolve?domain=@achlogadmin">Text us on Telegram</a>
                    </h5>
                    {% endif %}
                    
                    <button class='btn btn-success' disabled>Waiting for payment</button>
                    
                </div>
            </div>
        </div>
      </div>
               <!--POP UP-->
               
             <div class="modal fade show" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" style="display: none;" aria-modal="true">
                <div class="modal-dialog" role="document">
                   <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Tutorial</h5>
                        <button type="button" onClick = closeFunc() class="close"  data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">x</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Step 1: Deposit the price of the log you want to purchase.</p>
                        <p>Step 2: Choose the log you want to purchase and click Buy.</p>
                        <p>Step 3: Enter the email address to which your logs will be sent.</p>
                        <p>Step 4: An alert will appear, choose option use your available Balance.</p>
                        <p>Step 5: Wait for 1-5 mins for your logs to be sent to your email address.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" onClick="closeFunc()" class="btn btn-secondary" id="Close" data-dismiss="modal">Close</button>
                    </div>
                   </div>
                </div>
            </div>
        

            <script src="{% static 'js/index.js' %}"></script>
            <!--Start of Tawk.to Script-->
<script type="text/javascript">
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
	var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='https://embed.tawk.to/642e1c784247f20fefea12dc/1gta1uec9';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
	})();
	</script>
	<!--End of Tawk.to Script-->
   </body>
   <style>
            .wrapper{
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .card
        .card-body{
            padding: 1.5rem;
        }

        .btc{
            display: flex;
            justify-content: center;
        }

        .card
        .card-header{
            border: none;
        }

        .card{
            margin-bottom: 2.2rem;
            border: none;
        }

        .hove:active{
            color:#dc3545;
        }

   </style>
   <script type="text/javascript">
                var address="{{addr}}";
                var status="{{invoice_status}}";
                var socket = new WebSocket("wss://www.blockonomics.co/payment/" + address);

                socket.onmessage = function(event) {
                try {
                    var response = JSON.parse(event.data);
                    // This condition ensures that we reload only when we get a 
                    // new payment status and don't go into a loop
                    if (parseInt(response.status) > 0) {
                    setTimeout(function() { window.location.reload(); }, 1000);
                    }
                } catch (e) {
                    console.error("Error parsing JSON: ", e);
                }
                };

                socket.onerror = function(error) {
                console.error("WebSocket Error: ", error);
                };

                            
              </script>
   <script type="text/javascript">
    const socket = new WebSocket('wss://achlive.net/ws/achlive/?user_id={{request.user.pk}}');
    socket.onmessage = (event) => {
    console.log('Message received:', event.data);
    const data = JSON.parse(event.data);

    // Check if the message is "Payment confirmed"
    if (data.message === 'Payment confirmed') {
        const button = document.querySelector('.btn-success');

        // Enable the button and set the text to "Back home"
        button.removeAttribute('disabled');
        button.textContent = 'Back home';
    }

    // Handle other data received from the server as needed
};
</script>
</html>