account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from .import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm', from_email='Achlogs@achlive.net',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm), name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
  
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import (UserLoginForm)
urlpatterns = [
    path('longi/', admin.site.urls),
    path('', include('store.urls')),
    path('account/', include('account.urls', namespace="account")),
    path('pay/', include('payment.urls', namespace="payment")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name="payment"

urlpatterns=[
    path('buy/<int:pk>', views.buy, name='buy'),
    path('card/purchase',views.cards, name="cards"),
    path('add/', views.add_balance, name="coinbase"),
    path('send/', views.send_mail_kelly, name="send"),
    path('cards/', views.cards_mail, name="notify_cards"),
    path('balance/<int:pk>',views.track_balance, name='track_balance'),
    path('balance/receive/', views.receive_balance, name='receive_balance'),
]

templates/categorybase.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head><meta http-equiv="content-type" content="text/html;charset=UTF-8">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" 
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" 
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>ACHLOGS</title>

    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

    <link rel="stylesheet" href="{% static 'css/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<body>
    <div id="app">
        <div id="sidebar" class="active">
            <!------Sidebar start---------------->

            <div class="sidebar-wrapper active ps ps--active-y">
                <div class="sidebar-header">
                    <div class="d-flex justify-content-between">
                        <div class="logo">
                            <a href="{% url 'home' %}"><img src="#" alt="" srcset=""></a>
                        </div>
                        <div class="toggler">
                            <a href="#" class="sidebar-hide d-xl-none d-block"><i class="fa fa-close"></i></a>
                        </div>
                    </div>
                </div>
              <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title">Balance   ${% if balance %}{{balance}}{% else %}0.00{% endif %}</li>
                        <li class="sidebar-item  ">
                            <a href="{% url 'payment:coinbase' %}" class="sidebar-link">
                                <i class="fas fa-credit-card"></i>
                                <span>ADD BALANCE</span>
                            </a>
                        </li>

                        <li class="sidebar-item  ">
                            <!--<a href="cookies.php" class='sidebar-link'>-->
                            <!--    <i class="fas fa-credit-card"></i>-->
                            <!--    <span>Cookies</span>-->
                            <!--</a>-->
                        </li>

                        <li class="sidebar-item active ">
                            <a href="{% url 'home' %}" class="sidebar-link">
                                <i class="fa fa-dashboard"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        {% if product.name == "Decryptor" %}
                        {% else %}
                        
                        <li class="sidebar-item  has-sub">
                            <a href="#" class="sidebar-link">
                                <i class="fas fa-university"></i>
                                <span>USA BANKS</span>
                            </a>
                            <ul class="submenu ">
                                {% for category in usa %}
                                <li class="submenu-item ">
                                    <a href="{{category.get_absolute_url}}">{{category.name}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>

                        <li class="sidebar-item  has-sub">
                            <a href="#" class="sidebar-link">
                                <i class="fas fa-university"></i>
                                <span>CANADA BANKS</span>
                            </a>
                            <ul class="submenu ">
                                {% for category in canada %}
                                <li class="submenu-item ">
                                    <a href="{{category.get_absolute_url}}">{{category.name}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <!--<li class="sidebar-item  has-sub">
                            <a href="#" class="sidebar-link">
                                <i class="fas fa-university"></i>
                                <span>Pua&amp;Fullz</span>
                            </a>
                            <ul class="submenu ">
                                {% for category in pua %}
                                <li class="submenu-item ">
                                    <a href="alabama.php">{{category.name}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>-->

                        <li class="sidebar-item  has-sub">
                            <a href="#" class="sidebar-link">
                                <i class="fas fa-university"></i>
                                <span>EUROPEAN BANKS</span>
                            </a>
                            <ul class="submenu ">
                                {% for category in europe %}
                                <li class="submenu-item ">
                                    <a href="{{category.get_absolute_url}}">{{category.name}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% for category in categories %}
                        {% if category.name == "Extraction" %}
                        {% else %}
                        <li class="sidebar-item  ">
                            <a href="{{category.get_absolute_url}}" class="sidebar-link">

                                <span>{{category.name}}</span>
                            </a>
                        </li>
                        
                        {% endif %}
                        {% endfor %}
                        <li class="sidebar-item  ">
                            <a href="{% url 'account:dashboard' %}" class="sidebar-link">
                                <i class="fas fa-history"></i>
                                <span>PURCHASE HISTORY</span>
                            </a>
                        </li>

                        <!--<li class="sidebar-item  ">
                            <a href="reset.php" class="sidebar-link">
                                <i class="fas fa-lock"></i>
                                <span>Change Passowrd</span>
                            </a>
                        </li>-->
                        {% endif %}
                        <li class="sidebar-item  ">
                            <a href="{% url 'account:logout' %}" class="sidebar-link">
                                <i class="fas fa-power-off"></i>
                                <span>LOGOUT</span>
                            </a>
                        </li>
                        <li class="sidebar-item ">
                            <a href="tg://resolve?domain=@achliveadmin" class="sidebar-link"><i class="fa-brands fa-telegram"></i><span>Text us on Telegram</span></a>
                        </li>
                        
                
            
        </div>
        
    </div>
    
    
     <!------Sidebar end------------------>
    <div id="main">
        <header class="mb-3">
            <a href="#" class="burger-btn d-block d-xl-none">
                <i class="fa fa-bars"></i>
            </a>
        </header>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Scroll from left to right on the table to view more or tilt your phone.</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% block content %}{% endblock content %}
    </div>
    
    <script src="{% static 'js/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/vendor.js' %}"></script>
    <script src="{% static 'js/mains.js' %}"></script>
    <script src="{% static 'js/date.js' %}"></script>
	<script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/simple-datatables.js' %}"></script>
    <!--Start of Tawk.to Script-->
<script type="text/javascript">
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
	var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='https://embed.tawk.to/642e1c784247f20fefea12dc/1gta1uec9';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
	})();
	</script>
	<!--End of Tawk.to Script-->
    <style>
        .card-body {
            width: 800px;
            overflow-x: scroll;

        }

        @media screen and (max-width:900px) {
            .card-body {
                width: 300px;
            }
        }
    </style>
</body>
</html>