core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import (UserLoginForm)
urlpatterns = [
    path('longi/', admin.site.urls),
    path('', include('store.urls')),
    path('account/', include('account.urls', namespace="account")),
    path('pay/', include('payment.urls', namespace="payment")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name="payment"

urlpatterns=[
    path('buy/<int:pk>', views.buy, name='buy'),
    path('card/purchase',views.cards, name="cards"),
    path('add/', views.add_balance, name="coinbase"),
    path('send/', views.send_mail_kelly, name="send"),
    path('cards/', views.cards_mail, name="notify_cards"),
    path('balance/<int:pk>',views.track_balance, name='track_balance'),
    path('balance/receive/', views.receive_balance, name='receive_balance'),
]

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.new_home,name="new_home"),
    path('index/', views.home,name="home"),
    path('category/<slug:category_slug>', views.category_list, name='category_list'),
    path('random_names/', views.trial, name='random_name'),
    path('download/', views.download_csv, name='download'),
    path('download/balance/', views.download_balance, name='download_balance'),
    path('download/invoice/', views.download_invoice, name='download_invoice'),
    path('download/users/', views.download_users, name='download_users'),
    path('download/category/', views.download_category, name='download_category'),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
# Category Model
class Category(models.Model):
    STATUS_CHOICES = ((-1,'Side Menu'),(0,'USA Banks'), (1,"Canada Banks"), (2,"European Banks"),(3,"Pua and Fullz"))
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    location = models.IntegerField(choices=STATUS_CHOICES, default=-1)
    class Meta:
        verbose_name_plural = 'categories'
        
    def get_absolute_url(self):
        return reverse('category_list',args=[self.slug])
    def number(self):
        if self.id <= 5:
            return self.id * 5 + 3 
        else:
            return self.id * 2 + 4
    def __str__(self):
           return self.name
#PRODUCT MODEL      
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=255,help_text="Not shown but required")
    Balance = models.CharField(max_length=255,blank=True)
    Title = models.CharField(max_length=255,blank=True)
    Info = models.TextField(blank=True)
    slug = models.SlugField(max_length=255)
    price = models.FloatField( blank=True,null=True)
    Status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    pdf = models.FileField(null=True, blank=True, upload_to='pdfs/')
    
    
    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('created',)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

        # Check if the slug already exists
        if Product.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            # Add a unique suffix to the slug
            self.slug = f"{self.slug}-{self.pk}"
            self.save()
    
    def get_absolute_url(self):
        return reverse('front:product_detail',args=[self.slug])

    def __str__(self):
        return self.name
        

store/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import *
from payment.models import *
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .context_processors import random_name
from django.http import FileResponse
from django.conf import settings
import os
from account.models import *
@login_required
def home(request):
    if request.user.is_authenticated:
        invoice = Invoice.objects.filter(created_by=request.user).first()
        return render(request,"home.html",context={"invoice":invoice})
    
    return render(request,"home.html")
@login_required
def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'category.html', {'category': category, 'products': products})

def trial(request):
    
    return JsonResponse(random_name(request))

def download_csv(request):
    file_name = 'output.csv'  # Name of the CSV file
    file_path = os.path.join(settings.STATICFILES_DIRS[0], file_name)  # Replace with the actual path to the exported CSV file

    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            file_content = file.read()  # Read file contents into memory
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        response.write(file_content)  # Write the file content to the response
        return response
    else:
        return HttpResponse('File not found.')
    
def download_balance(request):
    file_name = 'balance.csv'  # Name of the CSV file
    file_path = os.path.join(settings.STATICFILES_DIRS[0], file_name)  # Replace with the actual path to the exported CSV file

    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            file_content = file.read()  # Read file contents into memory
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        response.write(file_content)  # Write the file content to the response
        return response
    else:
        return HttpResponse('File not found.')
    
def download_users(request):
    file_name = 'users.csv'  # Name of the CSV file
    file_path = os.path.join(settings.STATICFILES_DIRS[0], file_name)  # Replace with the actual path to the exported CSV file

    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            file_content = file.read()  # Read file contents into memory
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        response.write(file_content)  # Write the file content to the response
        return response
    else:
        return HttpResponse('File not found.')
    
def download_invoice(request):
    file_name = 'invoice.csv'  # Name of the CSV file
    file_path = os.path.join(settings.STATICFILES_DIRS[0], file_name)  # Replace with the actual path to the exported CSV file

    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            file_content = file.read()  # Read file contents into memory
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        response.write(file_content)  # Write the file content to the response
        return response
    else:
        return HttpResponse('File not found.')

def download_category(request):
    file_name = 'category.csv'  # Name of the CSV file
    file_path = os.path.join(settings.STATICFILES_DIRS[0], file_name)  # Replace with the actual path to the exported CSV file

    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            file_content = file.read()  # Read file contents into memory
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        response.write(file_content)  # Write the file content to the response
        return response
    else:
        return HttpResponse('File not found.')
    
def new_home(request):
    return render(request,"new_home.html")

store/templates/extraction.html
<html>
    {% load static %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<style>
    *{
margin: 0;
padding: 0;
box-sizing: border-box;
font-family: 'Poppins', sans-serif;
background: #5d626b;
}

.container{
width: 100%;
height: 100vh;
display: flex;
align-items: center;
justify-content: center;
}

.btan{
/*padding: 10px 60px;
background: gray;
border: 0;
outline: none;
cursor: pointer;
font-size: 22px;
font-weight: 500;
*/
width: 100%;
margin-top: 40px;
padding: 10px 40px;
background: #6fd649;
color: #fff;
border: none;
outline: none;
font-size: 18px;
border-radius: 4px;
cursor: pointer;
box-shadow: 0 5px 5px rgba(0,0,0,0.2);

}

.btn:hover{
background-color: #578859;
color: #fff;
}

.popup{
width: 400px;
background: #fff;
border-radius: 6px;
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
text-align: center;
/*padding: 0 0% 10%;*/
padding: 0 30px 30px;
color: #333;
}

.popup img{
width: 100px;
margin-top: -50px;
border-radius: 40%;
box-shadow: 0 2px 5px rgba(0,0,0,0.2);
}

.popup h2{
font-size: 38px;
font-weight: 500;
margin: 30px 0 10px;
background: #fff;
}
</style>
<div class="container">
    <div class="popup">
        <img src="{% static 'images/bg.jpg' %}" alt="Bitcoin,img">
        <h2>Achlive</h2>
        
        <p style="background: #fff;">Dear Customer,
            your bank log has been locked because you haven’t registered for buying logs .You have to purchase extraction. The extraction shows you’ve registered for buying logs. Kindly make a payment of $270. Once you pay for extraction you are given a free roll to all email access of any logs you buy
            Thank you</p>
        <a href="{% url 'payment:buy' pk=product.id %}"> 
            <button type="button" class="btan">Buy Extraction</button> 
        </a>
        
    </div>
</div>
</body>
</html>

store/templates/home.html
{% extends 'base.html' %}
	 <!------Sidebar end------------------>
	
	 	{% block content %}

		<div class="main-container" style="position:absolute ;right: 6rem;width: 70%;">
			<div class="container mt-5 ml-5">
				<div class="display-4 h5" style="
							color: rgb(255, 232, 232);
							padding-left: 5px;
							padding-right: 5px;
							font-size: 20px;
							margin-left: -15px;
						">
					WELCOME TO ACHLOGS
				</div>

				<div class="row">
					<div class="col-xs-12 col-md-4" style="padding-left: 5px; padding-right: 5px">
						<div class="kanban-col" tabindex="0">
							<div class="card-list">
								<div class="card-list-header">
									<h6 style="color: white;">Recently..</h6>
								</div>
								{% for category in category %}
								<div class="card-list-body" tabindex="0">
									<div class="card card-kanban" tabindex="0" style="background-color: #212029">
										<div class="card-body">
											<div class="card-title">
												<h6>
													{{category.name}}(full info)
												</h6>
												<p style="color: #fff">
													Added {{category.number}} items in
													category
													<a class="text-danger" href="{{category.get_absolute_url}}">{{category.name}}(full
														info)</a>
												</p>
											</div>

											<div class="card-meta d-flex justify-content-between">
												<span class="text-small date-time text-right" style="color: #fff">30-3-2023</span>
											</div>
										</div>
									</div>

									


								</div>
								{% endfor %}
							</div>
						</div>
					</div>

					<div class="col-xs-12 col-md-8" style="padding-left: 5px; padding-right: 5px">
						<div class="card">
							<div class="card-header" style="background-color: rgb(3, 3, 95);color:white">
								<span class="glyphicon glyphicon-calendar" style="color: #000;"></span>
								Browse our store, buy and invite your
								friends . Our store has been selling bank
								logs to millions of users in the darkweb! we
								have been working on spamming bank logs
								since 2017 and we maintain the position that
								"customers are always right" as long as the
								customer's actions or requests are not
								contrary to our store rules. If you need
								various bank logs and cashapp logs click on
								the dropdown menu to browse our Logs, After
								making a purchase, the log details will be
								sent to your email address and you will have
								a countdown of 48 hours to confirm the log
								details and if you have the correct cashout
								method


							</div>
						</div>



						<div class="card card-note" style="background-color: rgb(3, 3, 95);color:white">
							<div class="card-header">
								<div class="media align-items-center">
									<div class="media-body">
										<h6 class="mb-0 H6-filter-by-text" data-filter-by="text" style="color: white;">
											Our store is one of the best
											underground tools for selling
											websites owned by an anonymous
											hacktivist group. Our store is
											one of the best underground
											tools selling websites owned by
											the anonymous hacktivist group.
										</h6>
									</div>
								</div>
								<div class="d-flex align-items-center">
									<span data-filter-by="text" class="SPAN-filter-by-text"></span>
									<div class="ml-1 dropdown card-options">
										<button class="btn-options" type="button" id="note-dropdown-button-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

										</button>
										<div class="dropdown-menu dropdown-menu-right">
											<a class="dropdown-item" href="#">Mark As Read</a>
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>


		</div>
	</div>
{% endblock content %}	

store/templates/new_home.html
<!DOCTYPE html>
<html>
  {% load static %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body {
      background-image: url({% static 'images/iStock-1152537185.jpeg' %});
      background-repeat: no-repeat;
      background-size: cover;
    }

    .glass {
      margin-top: 20px;
      padding-left: 400px;
      padding-right: 400px;
    }

    .glass p {
      text-align: center;
      font-size: 25px;
      color: rgb(255, 255, 255);
      font-weight: 300;
      font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    }

    .quote svg {
      color: aliceblue;
      margin-left: 700px;
      margin-top: 20px;
    }

    .btn{
        margin-top: 15px;
        margin-left: 600px;
    }

    .btn button{
        height: 50px;
        width: 210px;
        font-size: 20px;
        border-radius: 30px;
        color: aliceblue;
        background-color: black;
        border-color: aliceblue;
        transition: background-color, 0.5s
    }
    .btn button:hover{
      background-color: red
    }

    @media screen and (max-width: 600px) {
        .glass {
      margin-top: 20px;
      padding-left: 50px;
      padding-right: 50px;
    }

    .btn{
        margin-top: 15px;
        margin-left: 100px;
    }

    .quote svg {
      color: aliceblue;
      margin-left: 200px;
      margin-top: 20px;
    }
    }
  </style>
</head>

<body>
  <div class="quote">
    <svg xmlns="http://www.w3.org/2000/svg" width="70" height="76" fill="currentColor" class="bi bi-quote" viewBox="0 0 16 16">
        <path d="M12 12a1 1 0 0 0 1-1V8.558a1 1 0 0 0-1-1h-1.388c0-.351.021-.703.062-1.054.062-.372.166-.703.31-.992.145-.29.331-.517.559-.683.227-.186.516-.279.868-.279V3c-.579 0-1.085.124-1.52.372a3.322 3.322 0 0 0-1.085.992 4.92 4.92 0 0 0-.62 1.458A7.712 7.712 0 0 0 9 7.558V11a1 1 0 0 0 1 1h2Zm-6 0a1 1 0 0 0 1-1V8.558a1 1 0 0 0-1-1H4.612c0-.351.021-.703.062-1.054.062-.372.166-.703.31-.992.145-.29.331-.517.559-.683.227-.186.516-.279.868-.279V3c-.579 0-1.085.124-1.52.372a3.322 3.322 0 0 0-1.085.992 4.92 4.92 0 0 0-.62 1.458A7.712 7.712 0 0 0 3 7.558V11a1 1 0 0 0 1 1h2Z"/>
      </svg>
  </div>
  <div class="glass">
    <p>Our store embodies a self-written engine, anti-DDoS system and a bulletproof server. Logs are re checked and updated after each occurrence of issuing bulk purchases. Please do not hesitate to contact the support team if you encounter any issue.</p>
    <p>Please take the time to read through our policies. The store disclaims any responsibility for any additional actions you take with the purchased log in your possession. Funds sent to the store will be allocated to the user after two confirmations. Get in touch with the <a href="#">SUPPORT TEAM</a>, in case of any queries or inquiries.</p>
    <p>A token would be issued to any account after three instant purchases or a deposit of more than $1000. Accounts that have been inactive for six months will be deactivated.</p>
  </div>

  <div class="btn">
    <a href="{% url 'home' %}"><button>continue</button></a>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>